### ISSUE TITLE
Duplicate class

### ISSUE THREAD

**Issue by kostricanitechnology** [googlemaps/flutter-navigation-sdk#244]
Hello,

We are using google maps and google naviation for our app but are getting this error ` Duplicate class com.google.android.gms.maps.model.VisibleRegion found in modules jetified-navigation-6.0.0-runtime (com.google.android.libraries.navigation:navigation:6.0.0) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)` It looks a conflict between both packages.

Can you help how to resolve this issue?

Thanks

**Comment by v62win** [comment]
i am facing this too how to fix this

**Comment by jokerttu** [comment]
The issue is known and explained here:
https://github.com/googlemaps/flutter-navigation-sdk?tab=readme-ov-file#compatibility-with-other-libraries

You could override the depelendies on your local android and ios projects, to allow using both packages, but in this case you must be sure that packases implementing the libraries are reallty using same maps sdk version to avoid build errors. This is not recommended solution because possible compability issues if versions mismatch.

Note that this package has separate Google Maps view that supports all common use cases.
If `google_maps_flutter` package has something that this package is missing, please file separate issue with feature_request label.

**Comment by kostricanitechnology** [comment]
I already have excluded them on the build.gradle and also forced to use all same version but still getting same issue

```
dependencies {
    implementation "androidx.core:core-ktx:1.12.0"
    implementation "com.google.android.gms:play-services-maps:18.2.0"
    implementation "com.google.android.gms:play-services-location:21.0.1"
}
configurations.all {
    resolutionStrategy {
        force "com.google.android.gms:play-services-maps:18.2.0"
        force "com.google.android.gms:play-services-location:21.0.1"
    }
}
```

**Comment by kostricanitechnology** [comment]
Can anyone help with this?
